using MongoDB.Bson;

namespace Tharga.Team.MongoDB.Tests;

/// <summary>
/// A team names itself: <see cref="TeamEntityBase{T}.ToString"/> returns the team's name rather than the
/// record dump the compiler would otherwise synthesize (Tharga/Team#254).
/// </summary>
/// <remarks>
/// Radzen's dropdown writes <c>Value.ToString()</c> into a hidden accessible input — both its
/// <c>value</c> and its <c>aria-label</c> — and ignores <c>TextProperty</c> there, so a synthesized
/// dump reaches the DOM of every page carrying a team selector. There is no Radzen parameter that
/// overrides it, which is why the fix belongs on the entity.
/// <para>
/// The assertions deliberately run against **derived** records rather than the base. A record
/// re-synthesizes its own <c>ToString()</c> in every declaration unless a base declares a *sealed*
/// override, so a plain <c>override</c> would be silently regenerated by each host's
/// <c>record TeamEntity : TeamEntityBase&lt;TeamMember&gt;;</c> — leaving the defect exactly where it
/// was reported while a test against the base passed. Asserting on a subclass is what makes the
/// <c>sealed</c> keyword load-bearing rather than decorative.
/// </para>
/// </remarks>
public class TeamEntityToStringTests
{
    private const string TeamName = "Arjeplogs kommun";

    public record TestMember : TeamMemberBase;

    /// <summary>Stands in for a host's own entity, including properties the toolkit never sees.</summary>
    public record HostTeamEntity : TeamEntityBase<TestMember>
    {
        public string SyncedIconReference { get; init; }
        public string SyncedIconSource { get; init; }
    }

    [Fact]
    public void The_shipped_entity_names_itself()
    {
        var team = new DefaultTeamEntity { Key = "ArjeplogsKommun", Name = TeamName, Members = [] };

        Assert.Equal(TeamName, team.ToString());
    }

    [Fact]
    public void A_host_defined_entity_names_itself()
    {
        var team = new HostTeamEntity
        {
            Key = "ArjeplogsKommun",
            Name = TeamName,
            Members = [],
            SyncedIconReference = "e4ef2c7e64d64cad8a254feab016b80f",
            SyncedIconSource = "https://yt3.ggpht.com/ytc/AKedOLT54s64ewm5vaxOp1KxLwCGH1DiVXMMm39HXfdY0g"
        };

        Assert.Equal(TeamName, team.ToString());
    }

    /// <summary>
    /// The exposure half of #254, asserted on what a host would actually add rather than on the shape of
    /// the dump: the id, the access level and an external URL must not be reachable through
    /// <c>ToString()</c>.
    /// </summary>
    [Fact]
    public void No_internal_state_leaks_through_the_rendered_label()
    {
        var team = new HostTeamEntity
        {
            Id = ObjectId.Parse("6a6f5433317a6a5d3720a978"),
            Key = "ArjeplogsKommun",
            Name = TeamName,
            Members = [],
            ConsentAccessLevel = AccessLevel.Administrator,
            SyncedIconSource = "https://yt3.ggpht.com/ytc/AKedOLT54s64ewm5vaxOp1KxLwCGH1DiVXMMm39HXfdY0g"
        };

        var rendered = team.ToString();

        Assert.DoesNotContain("6a6f5433317a6a5d3720a978", rendered);
        Assert.DoesNotContain("Administrator", rendered);
        Assert.DoesNotContain("https://", rendered);
        Assert.DoesNotContain("{", rendered);
    }
}
